services:
  - type: web
    name: groceries-api
    env: docker
    branch: main
    dockerfilePath: api/Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: groceries-db
          property: connectionString
      - key: CATALOG_RUN_ON_START
        value: "0"
      - key: DISABLE_CATALOG_SCHEDULE
        value: "1"

  - type: web
    name: groceries-frontend
    env: docker
    branch: main
    dockerfilePath: frontend/Dockerfile
    plan: starter
    envVars:
      - key: GROCERIES_API_URL
        value: http://groceries-api:8000
      - key: DATABASE_URL
        fromDatabase:
          name: groceries-db
          property: connectionString

databases:
  - name: groceries-db
    databaseName: groceries
    plan: starter
