services:
  - type: web
    name: groceries-api
    env: docker
    dockerfilePath: api/Dockerfile
    branch: main
    plan: free
    startCommand: uvicorn api.service:app --host 0.0.0.0 --port $PORT
    buildCommand: |
      pip install -r requirements.txt
    envVars:
      - key: DATABASE_URL
        scope: PRIVATE

  - type: web
    name: groceries-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    branch: main
    plan: free
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    buildCommand: |
      pip install -r requirements.txt
    envVars:
      - key: GROCERIES_API_URL
        value: https://groceries-api.onrender.com
        scope: PRIVATE
